### PR TITLE
add a reduced isLoaded() syntax & typo3 11.5 support

### PR DESCRIPTION
**Pull request by xerc**
btw/ are you interested in `PHP CS Fixer` and cleanup of the source ? might even do a logo conversion from PNG to SVG

### CODE REVIEW

**Comment by franzholz** [comment]
> btw/ are you interested in `PHP CS Fixer` and cleanup of the source ?

Yes. If this pull request is closed, then please open a new pull request with suggested PHP improvements.

**Comment by xerc** [comment]
https://github.com/franzholz/patch10011/compare/master...xerc:cleanup

**Comment by franzholz** [comment]
> [master...xerc:cleanup](https://github.com/franzholz/patch10011/compare/master...xerc:cleanup)

Only the xerc:master branch is used in the Pull Request.
And please undo a change according to the above Review comment and reduce 1 return.

**Comment by xerc** [comment]
> undo a change according to the above Review comment and reduce 1 return

this is how it should be; to have clean/kernel-like and speedy code - if you are not happy do not include this part of the PR

**Comment by franzholz** [comment]
> if you are not happy do not include this part of the PR

I am afraid that I can only merge all commits from the PR without a possibility to exclude 1 commit.

**Comment by xerc** [comment]
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project

**Pull request merged**
